<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-DJ4FDME" failures="1" tests="1" name="Test(failed)" time="0.12" errors="0" timestamp="2024-07-26T22:12:51 IST">
  <testcase classname="testNGDemo.FirstTestScenario3" name="second_testcase" time="0.03">
    <failure type="java.lang.AssertionError" message="expected [Testing] but found [Test]">
      <![CDATA[java.lang.AssertionError: expected [Testing] but found [Test]
at testNGDemo.FirstTestScenario3.second_testcase(FirstTestScenario3.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="testNGDemo.FirstTestScenario3" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testNGDemo.FirstTestScenario3" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testNGDemo.FirstTestScenario3" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="testNGDemo.FirstTestScenario3" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testNGDemo.FirstTestScenario3" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
</testsuite> <!-- Test(failed) -->
